name: "TrustProfile and reviews"

readme:

    tags: |
        trustprofile, trust, profile, reviews, sidebar

    intro: |
        Collect reviews and earn trust badges to show on your webshop. Don't keep losing revenue. Show you can be trusted!

    description: |
        **DON'T KEEP LOSING CUSTOMERS. SHOW YOU CAN BE TRUSTED.**

        Presenting your trustworthiness on your shop is possible with our innovative tools. You can show them at a glance, what will lead to increase your sales. The tools are specifically designed for showing trust without customers having to leave your shop.

        **Send review invitations automatically**

        Our integrations allow you to invite your customer automatically for leaving a review. You can decide whenever you want these invitations to go out. How easy is that?

        **Show your review rating on your webshop**

        With this plugin our sidebar shows your combined rating directly on your shop. Meaning your webshop visitor does not have to leave your shop to see the collected reviews! Other presentation items you can add to your webshop using html code.

        **Earn trust badges to show more trust!**

        TrustProfile rewards good entrepreneurs. Are you a good entrepreneur? Show you can are reliable by using our trustbadges. Verify your webshops identity with our automatic checks and connect your existing trust sources to unlock all our trust badges. Will your webshop earn them all?

        **Fake reviews**

        Several controls are in place to prevent fake reviews. What checks do we use? Sorry, that’s our little secret! Every day we aim to upgrade our security systems in order to guarantee the authenticity of reviews.

        **TRUSTPROFILE BETA – FREE OF USE**

        Register at: [www.trustprofile.io](https://www.trustprofile.io)

        After a year of development, we are ready for users all around the globe. We start with a beta phase in which we don’t charge for use. With your help, we can further improve our software until we are ready to launch for real. After the launch later this year we will offer a freemium package and a number of paid packages based on the number of invitations you send. As a reward you receive one year free of charge!
