name: "Trustprofile and reviews"

readme:

    tags: |
        trustprofile, trust, profile, reviews, sidebar

    intro: |
        Collect reviews and earn trust badges to show on your webshop. Don't keep losing revenue. Show you can be trusted!

    description: |
        **DON'T KEEP LOSING CUSTOMERS. SHOW YOU CAN BE TRUSTED.**

        Presenting your trustworthiness on your shop is possible with our innovative tools. You can show them at a glance, what will lead to increase your sales. The tools are specifically designed for showing trust without customers having to leave your shop.

        **Send review invitations automatically**

        Our integrations allow you to invite your customer automatically for leaving a review. You can decide whenever you want these invitations to go out. How easy is that?

        **Show your review rating on your webshop**

        With this plugin our sidebar shows your combined rating directly on your shop. Meaning your webshop visitor does not have to leave your shop to see the collected reviews! Other presentation items you can add to your webshop using html code.

        **Earn trust badges to show more trust!**

        Trustprofile rewards good entrepreneurs. Are you a good entrepreneur? Show you are reliable by using our trustbadges. Verify your webshops identity with our automatic checks and connect your existing trust sources to unlock all our trust badges. Will your webshop earn them all?

        **Present your trust label on your shop!**

        Trustprofile is the official software partner of several online trustmarks. With our software you can present your trustmark perfectly on your website. There is a sidebar and various banners available for the trustmarks. They are at the moment:
        Germany: EHI Geprüfter Online - Shop
        Netherlands: WebwinkelKeur
        Belgium: Becom
        Croatia: eCommerce Hrvatska

        **Fake reviews**

        Several controls are in place to prevent fake reviews. What checks do we use? Sorry, that’s our little secret! Every day we aim to upgrade our security systems in order to guarantee the authenticity of reviews.

        **A trust profile should be affordable to all shops**
        Claim your Trustprofile, present our widgets at your webshop and manage the reviews you will recieve.
        We offer 3 paid plans which are invoiced every year. All of these plans are very affordable and flexible. Check out our plans at: www.trustprofile.com/en/business/plans

        Register at: [www.trustprofile.com](https://www.trustprofile.com)
        
        To make use of our product reviews feature we will need authorization to gather some of your product data.
        Our system needs this data to properly assign the written review to the right product.

    screenshots: |
        1. Screenshot of Trustprofile webshop page
        2. Trustprofile member page on mobile phone
        3. Trustprofile badges on mobile phone
        4. Trustprofile member page on desktop
        5. Sidebar hovered
        6. Trustprofile review widget
        7. Trustprofile badges
        8. Trustprofile review source
        9. Trustprofile on different devices